#pragma once
#ifndef GBKFIT_BUILD_SETTINGS_HPP
#define GBKFIT_BUILD_SETTINGS_HPP

#define GBKFIT_BUILD_CUDA
#define GBKFIT_BUILD_FFTW3
#define GBKFIT_BUILD_DMODEL_MMAPS
#define GBKFIT_BUILD_DMODEL_MMAPS_CUDA
#define GBKFIT_BUILD_DMODEL_MMAPS_OMP
#define GBKFIT_BUILD_DMODEL_SCUBE
#define GBKFIT_BUILD_DMODEL_SCUBE_CUDA
#define GBKFIT_BUILD_DMODEL_SCUBE_OMP
#define GBKFIT_BUILD_GMODEL_GMODEL01
#define GBKFIT_BUILD_GMODEL_GMODEL01_CUDA
#define GBKFIT_BUILD_GMODEL_GMODEL01_OMP
/* #undef GBKFIT_BUILD_MODEL_MODEL01 */
/* #undef GBKFIT_BUILD_MODEL_MODEL01_CUDA */
/* #undef GBKFIT_BUILD_MODEL_MODEL01_OMP */
#define GBKFIT_BUILD_FITTER_MPFIT
#define GBKFIT_BUILD_FITTER_MULTINEST

#endif // GBKFIT_BUILD_SETTINGS_HPP
