#pragma once
#ifndef GBKFIT_BUILD_SETTINGS_HPP
#define GBKFIT_BUILD_SETTINGS_HPP

#define GBKFIT_BUILD_CUDA
#define GBKFIT_BUILD_FFTW3
#define GBKFIT_BUILD_FITTER_MPFIT
#define GBKFIT_BUILD_FITTER_MULTINEST
#define GBKFIT_BUILD_MODEL_MODEL01
#define GBKFIT_BUILD_MODEL_MODEL01_CUDA
#define GBKFIT_BUILD_MODEL_MODEL01_OMP

#endif // GBKFIT_BUILD_SETTINGS_HPP
